### ISSUE TITLE
Loop infinito

### ISSUE THREAD

**Issue by Giovanni-Bruno** [wendellcamillo/Source-Code-Inspection#1]
Classe : Troco
Linhas: 16,21,26,31,36,41
Descrição: Loop infinito para números menores que os da comparação respectivamente: 100,50,20,10,5,2
Categoria: Lógica
Severidade: Grave

**Comment by wendellcamillo** [comment]
*Erro de percepção*

Realmente, o comando expresso por

        while (valor % 100 != 0) {
            count++;
        }

e todos os valores seguidamente não condizem com laço infinito. Para cada moeda, enquanto o resto da divisão do valor que entrou na máquina não fosse zero, e passasse para a próxima moeda, até a última, o contatos acrescentava mais uma unidade, para calcular o quando de troco deveria devolver.
