### ISSUE TITLE
Exception de Saldo Vazias

### ISSUE THREAD

**Issue by wendellcamillo** [wendellcamillo/Source-Code-Inspection#10]
Classe : SaldoInsuficienteException
Linhas: 7, 8
Descrição: Exception não retorna nenhuma menagem para avisar erro
Categoria: Comissão
Severidade: Baixo

**Comment by Giovanni-Bruno** [comment]
Resolvido.
Contrutor padrão da classe alterado para adicionar mensagem de erro.
