### ISSUE TITLE
Laço implemtado de forma incorreta

### ISSUE THREAD

**Issue by Giovanni-Bruno** [wendellcamillo/Source-Code-Inspection#11]
Classe: Troco.java
Linha(s): 61, 62, 63, 64
Descrição: Laço implentado de forma incorreta
Categoria: Dados
Severidade: Alta

**Comment by wendellcamillo** [comment]
Correção:        

@Override
        public boolean hasNext() {
            for (int i = 6; i==0; i--) {
                if (troco.papeisMoeda[i] != null) {
                    return true;
                }
            }
            return false;
        }
