### ISSUE TITLE
Código Implementado Erroneamente

### ISSUE THREAD

**Issue by wendellcamillo** [wendellcamillo/Source-Code-Inspection#13]
Classe : TicketMachine
Linhas: 43-52
Descrição: Saldo não é atualizado antes de sua impressão, é impresso somente o mesmo saldo
Categoria: Comissão
Severidade: Muito alto

**Comment by Giovanni-Bruno** [comment]
Resolvido.
Saldo agora é subtraído corretamente - linha 52, classe TicketMachine
