### ISSUE TITLE
Variável de nome diferente

### ISSUE THREAD

**Issue by Giovanni-Bruno** [wendellcamillo/Source-Code-Inspection#2]
Classe: TicketMachine.java
Linha: 17
Descrição: Variável de nome diferente da documentação (No construtor está com nome diferente).
Categoria: Comissão
Severidade: Baixo

**Comment by wendellcamillo** [comment]
public class TicketMachine {

    protected int precoDoBilhete;
    protected int saldo;
    protected int[] papelMoeda = {2, 5, 10, 20, 50, 100};

    public TicketMachine(int precoDoBilhete) {
        this.precoDoBilhete = precoDoBilhete;
        this.saldo = 0;
    }
}
