### ISSUE TITLE
Comando de laço infinito.

### ISSUE THREAD

**Issue by Giovanni-Bruno** [wendellcamillo/Source-Code-Inspection#8]
Classe: Troco.java
Linha(s): 16
Descrição: Comando de laço infinito.
Categoria: Desempenho
Severidade: Muito Alto

**Comment by wendellcamillo** [comment]
*Erro de percepção*

Realmente, o comando expresso por

        while (valor % 100 != 0) {
            count++;
        }

e todos os valores seguidamente não condizem com laço infinito. Para cada moeda, enquanto o resto da divisão do valor que entrou na máquina não fosse zero, e passasse para a próxima moeda, até a última, o contatos acrescentava mais uma unidade, para calcular o quando de troco deveria devolver.
