### ISSUE TITLE
Posição de vetor inexistente.

### ISSUE THREAD

**Issue by Giovanni-Bruno** [wendellcamillo/Source-Code-Inspection#9]
Classe: Troco.java
Linha(s): 14
Descrição: Posição de vetor inexistente.
Categoria: Dados
Severidade: Alta

**Comment by wendellcamillo** [comment]
*Erro de identificação*

De início, pensamos que o vetor criado não satisfazia o conjunto de valores necessários para as cédulas, mas visualizamos em seguida que sim, o vetor criado tem 6 posições, e os valores são preenchidos de 0 a 5 no vetor.

papeisMoeda = new PapelMoeda[6];
